Backend/Backend/urls.py
from email.mime import base
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Endpoint.urls', namespace='Endpoint')),
]

Backend/Endpoint/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'Endpoint'

urlpatterns =[
    path('', views.home, name='home' ),
    path('grupo/', views.group.as_view(), name='grupo' ),
    path('novogrupo/', views.create_group, name='novogrupo' ),
    path('editargrupo/<int:id>/', views.edit_group, name='editargrupo'),
    path('meusgrupos/', views.list_group, name='meusgrupos' ),
    path('minhascarteiras/', views.home_caixas, name='minhascarteiras' ),
    path('vercarteira/<int:id>/', views.create_financas, name='vercarteira' ),
    path('calcularobjetico/', views.calcular_objetivo, name='calcularobjetico'),
    path('comentarios/', views.comentarios, name='comentarios'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Backend/templates/grupo/aviso_criar_grupo.html
{% extends 'base.html' %}

{% block title %}Novo Grupo - Aviso{% endblock %}

{% block content %}
<div>
    {% for email in aviso_email %}
    <p>
        E-mail {{email}} não encontrado, convite enviado para e-mail. 
    </p>
    {% endfor %}
</div>
{% endblock %}

Backend/templates/grupo/criar_grupo.html
{% extends 'base.html' %}

{% block title %}Novo Grupo{% endblock %}

{% block content %}
    <form action="{% url 'Endpoint:novogrupo' %}" method='post'>
        {% csrf_token %}
        <div>
            <label>Nome do grupo: </label>
            <input id="GpName" name="GpName" type="text" class="form-control">
        </div>
        <div>
            <label>Status do Grupo</label>
            <select id="GpStats" name="GpStats" class="form-control">
                <option value="True">Ativo</option>
                <option value="False">inativo</option>
            </select>
        </div>
        <div style="padding-bottom: 20px;">
            <label>Adicionar pessoas ao grupo:</label>
            <input id="GpUse" name="GpUse" type="text" placeholder="joao@email.com" class="form-control">
        </div>
        <div>
            <input type="submit" value="Salvar" class="form-control btn btn-success">
        </div>

    </form>
{% endblock %}

Backend/templates/grupo/editargrupo.html
{% extends 'base.html' %}

{% block title %}Editar Grupo{% endblock %}

{% block content %}
    <form action="/editargrupo/{{grupo.GpId}}" method='post'>
        {% csrf_token %}

        <p>
            <label>Nome do Grupo: </label>
            <input type="text" id="GpName" name="GpName" value="{{grupo.GpName}}" class="form-control"/>
        </p>
        <p>
            <label>Status do Grupo</label>
            <select id="GpStats" name="GpStats" class="form-control">
                <option value="True">Ativo</option>
                <option value="False">inativo</option>
            </select>
        </p>
        <p>
            <label>Pessoas ao grupo:</label>
            <input id="GpUse" name="GpUse" type="text" value="{{all_users}}" class="form-control"/>
            <p style="color: red;">
                ** Para remover ou adicionar novas pessoas ao grupo, basta remove-los ou adiciona-los a lista **
            </p>
        </p>
        <p>
            <input type="submit" value="Salvar" class="form-control btn btn-success">
        </p>
    </form>

{% endblock %}

Backend/templates/grupo/grupo.html
{% extends 'base.html' %}

{% block title %}Grupos{% endblock %}

{% block content %}
    <div class="container" style="padding-bottom: 20px;">
        <div class="row">
            <div class="col-sm"><a href="{% url 'Endpoint:novogrupo' %}">Novo Grupo</a></div>
            <div class="col-sm"><a href="{% url 'Endpoint:meusgrupos' %}">Meus Grupos</a></div>
        </div>        
    </div>
    <hr class="sidebar-divider my-0">
    <div style="margin-top: 20px;">
        <div>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col"><h1>Meus Grupos</h1></th>
                  </tr>
                </thead>
                <tbody>                    
                    {% for gp in grupos %}
                        <tr>
                            <td><a href="/editargrupo/{{gp.Groups.GpId}}" >{{gp.Groups.GpName}}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    
{% endblock %}