Backend/Backend/urls.py
from email.mime import base
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Endpoint.urls', namespace='Endpoint')),
]

Backend/Endpoint/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'Endpoint'

urlpatterns =[
    path('', views.home, name='home' ),
    path('grupo/', views.group.as_view(), name='grupo' ),
    path('novogrupo/', views.create_group, name='novogrupo' ),
    path('editargrupo/<int:id>/', views.edit_group, name='editargrupo'),
    path('meusgrupos/', views.list_group, name='meusgrupos' ),
    path('minhascarteiras/', views.home_caixas, name='minhascarteiras' ),
    path('vercarteira/<int:id>/', views.create_financas, name='vercarteira' ),
    path('calcularobjetico/', views.calcular_objetivo, name='calcularobjetico'),
    path('comentarios/', views.comentarios, name='comentarios'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Backend/templates/comentarios.html
{% extends 'base.html' %}

{% block title %}Comentarios{% endblock %}

{% block content %}
    
        <div class="container" style="padding-bottom: 20px;">
            <form action="{% url 'Endpoint:comentarios' %}" method='post'>
                <div class="row">                                
                    <div class="col-sm">
                        {% csrf_token %}
                        <label>Digite seu comentario: </label>
                        <textarea class="form-control" id="mensagem" name="mensagem" type="area"></textarea>
                    </div>
                    <!-- <div class="col-sm">
                        <label>Nota para o sistema:</label>
                        <input class="form-control" id="score" name="score" type="range" min="0" max="5">
                    </div> -->
                    <div class="col-sm">
                        <label>- -</label>
                        <input class="form-control btn btn-primary" type="submit" value="Calcular">
                    </div> 
                </div>
            </form>
        </div>
    

    <div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Mensagem</th>
                <th scope="col">Mensagem traduzida</th>
                <th scope="col">Nota IA Logis</th>
              </tr>
            </thead>
            <tbody>
                {% for coment in coments %}
                    <tr>
                        <td>{{coment.CmMessage}}</td>
                        <td>{{coment.CmMessageEnglish}}</td>
                        <td>{{coment.CmScoreIA_logistica}}</td>
                    </tr>
                {% endfor %}      
            </tbody>
          </table>
    </div>
{% endblock %}

Backend/templates/config.html
{% extends 'base.html' %}
{% block title %}Configurações{% endblock %}
{% block content %}

{% endblock %}

Backend/templates/home.html
{% extends 'base.html' %}

{% block title %}Gerenciador{% endblock %}

{% block content %}
    <!--<meta http-equiv="refresh" content="5" > -->
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    {% for caixa in caixas %}     
        <div id="entrada{{caixa.CaixaGrupo.GpName}}" style="height: 370px; width: 100%;"></div>
        <div id="saida{{caixa.CaixaGrupo.GpName}}" style="height: 370px; width: 100%;"></div>
    {% endfor %}
        <script>
            window.onload = function() {
            {% for caixa in caixas %}   
                var entrada{{caixa.CaixaGrupo.GpName}} = new CanvasJS.Chart("entrada{{caixa.CaixaGrupo.GpName}}", {
                    animationEnabled: true,
                    title: {
                        text: "{{caixa.CaixaGrupo.GpName}} - Entrada"
                    },
                    data: [{
                        type: "pie",
                        startAngle: 240,
                        yValueFormatString: "##0.00\"%\"",
                        indexLabel: "{label} {y}",
                        dataPoints: [
                            {% for n in financas %}
                                {% for financa in n %}
                                    {% if financa.FinancaStats == True %}
                                        {% if financa.CaixaFinanca.CaixaID == caixa.CaixaID %}
                                            {% if financa.FinancaType == True %}
                                                {y: {{financa.Financaporcentagem}}, label: "{{financa.FinancaName}}"},
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        ]
                    }]
                });
                entrada{{caixa.CaixaGrupo.GpName}}.render();
                
                var saida{{caixa.CaixaGrupo.GpName}} = new CanvasJS.Chart("saida{{caixa.CaixaGrupo.GpName}}", {
                    animationEnabled: true,
                    title: {
                        text: "{{caixa.CaixaGrupo.GpName}} - Saida"
                    },
                    data: [{
                        type: "pie",
                        startAngle: 240,
                        yValueFormatString: "##0.00\"%\"",
                        indexLabel: "{label} {y}",
                        dataPoints: [
                            {% for n in financas %}
                                {% for financa in n %}
                                    {% if financa.FinancaStats == True %}
                                        {% if financa.CaixaFinanca.CaixaID == caixa.CaixaID %}
                                            {% if financa.FinancaType == False %}
                                                {y: {{financa.Financaporcentagem}}, label: "{{financa.FinancaName}}"},
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        ]
                    }]
                });
                saida{{caixa.CaixaGrupo.GpName}}.render();
            {% endfor %}
            }
        </script>
        

{% endblock %}