Backend/Backend/urls.py
from email.mime import base
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('Endpoint.urls', namespace='Endpoint')),
]

Backend/Endpoint/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'Endpoint'

urlpatterns =[
    path('', views.home, name='home' ),
    path('grupo/', views.group.as_view(), name='grupo' ),
    path('novogrupo/', views.create_group, name='novogrupo' ),
    path('editargrupo/<int:id>/', views.edit_group, name='editargrupo'),
    path('meusgrupos/', views.list_group, name='meusgrupos' ),
    path('minhascarteiras/', views.home_caixas, name='minhascarteiras' ),
    path('vercarteira/<int:id>/', views.create_financas, name='vercarteira' ),
    path('calcularobjetico/', views.calcular_objetivo, name='calcularobjetico'),
    path('comentarios/', views.comentarios, name='comentarios'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Backend/templates/caixa/calculo.html
{% extends 'base.html' %}

{% block title %}Calculo de Rendimentos{% endblock %}

{% block content %}
    
        <div class="container" style="padding-bottom: 20px;">
            <form action="{% url 'Endpoint:calcularobjetico' %}" method='post'>
                <div class="row">                                
                    <div class="col-sm">
                        {% csrf_token %}
                        <label>Valor para aplicação: </label>
                        <input class="form-control" id="principal" name="principal" step="0.01" type="number">
                    </div>
                    <div class="col-sm">
                        <label>Periodo em meses:</label>
                        <input class="form-control" id="periodo" name="periodo" type="number">
                    </div>
                    <div class="col-sm">
                        <label>Juros por mes:</label>
                        <input class="form-control" id="juros" name="juros" type="number" step="0.01" placeholder="0.15">
                    </div>
                    <div class="col-sm">
                        <label>- -</label>
                        <input class="form-control btn btn-primary" type="submit" value="Calcular">
                    </div> 
                </div>
            </form>
        </div>
    

    <div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Valor Total</th>
                <th scope="col">Periodo em meses</th>
                <th scope="col">Juros por mes %</th>
                <th scope="col">Rendimento Bruto</th>
                <th scope="col">Montante</th>
              </tr>
            </thead>
            <tbody>
                <td>R$ {{total}}</td>
                <td>{{periodo}}</td>
                <td>{{jurosmes}}</td>
                <td>{{juros}}</td>
                <td>R$ {{montante}}</td>
            </tbody>
          </table>
    </div>
{% endblock %}

Backend/templates/caixa/home_caixas.html
{% extends 'base.html' %}

{% block title %}Carteira{% endblock %}

<p>{{caixas}}</p>

{% block content %}
    <hr class="sidebar-divider my-0">
    <div style="margin-top: 20px;">
        <div>
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col"><h1>Minhas Carteiras</h1></th>
                  </tr>
                </thead>
                <tbody>                    
                    {% for caixa in caixas %}
                        <tr>
                            <td><a href="/vercarteira/{{caixa.CaixaID}}" >{{caixa.CaixaGrupo.GpName}}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    
{% endblock %}

Backend/templates/caixa/ver_caixa.html
{% extends 'base.html' %}

{% block title %}Carteira{% endblock %}

{% block content %}


    <div style="display: flex;">
        <button class="btn btn-primary" onclick="openForm()">Adicionar Entrada/Saida</button>

        <p style="text-align: center; margin: 0; margin-left: 15%;  top: 50%; left: 50%;">Total da Carteira: R${{total}}</p>
    </div>
    
    

    <!-- The form -->
    <div class="form-popup" id="myForm">
        <form action="/vercarteira/{{id}}/" class="form-container" method='post'>
            {% csrf_token %}
            <h2>Novo lançamento</h2>
            
            <input style="display: none;" type="text" name="tipo" value="novo">

            <label for="FinancaType"><b>Tipo de Lançamento:</b></label>
            <select class="form-control" id="FinancaType" name="FinancaType" required>
                <option value="True">Entrada</option>
                <option value="False">Saida</option>
            </select>

            <p style="padding-top: 10px;"></p>  

            <label for="FinancaName"><b>Nome do lançamento:</b></label>
            <input class="form-control" type="text" name="FinancaName" placeholder="Mercado" required>

            <p style="padding-top: 10px;"></p>            

            <label for="FinancaType"><b>Valor:</b></label>
            <input class="form-control" type="number" name="FinancaValue" step="0.01" placeholder="00.1" required>

            <p style="padding-top: 10px;"></p>  

            <button type="submit" class="btn">Salvar</button>
            <button type="button" class="btn cancel" onclick="closeForm()">Cancelar</button>
        </form>
    </div>

    <div style="margin-top: 20px;">
        {% for financa in financas %}
            <div class="form-popup" id="myForm{{financa.FinancaID}}">
                <form action="/vercarteira/{{id}}/" class="form-container" method='post'>
                    {% csrf_token %}
                    <h2>Editar {{financa.FinancaName}}</h2>
                    
                    <input style="display: none;" type="text" name="tipo" value="{{financa.FinancaID}}">

                    <label for="FinancaType"><b>Tipo de Lançamento:</b></label>
                    <select class="form-control" id="FinancaType" name="FinancaType" >
                        <option value="True">Entrada</option>
                        <option value="False">Saida</option>
                    </select>

                    <p style="padding-top: 10px;"></p>  

                    <label for="FinancaName"><b>Nome do lançamento:</b></label>
                    <input class="form-control" type="text" name="FinancaName" placeholder="{{financa.FinancaName}}" >

                    <p style="padding-top: 10px;"></p>            

                    <label for="FinancaType"><b>Valor:</b></label>
                    <input class="form-control" type="number" name="FinancaValue" step="0.01" placeholder="{{financa.FinancaValue}}">

                    <p style="padding-top: 10px;"></p>  

                    <label for="FinancaStats"><b>Deletar?</b></label>
                    <select class="form-control" id="FinancaStats" name="FinancaStats">
                        <option value="True">Não</option>
                        <option value="False">Sim</option>
                    </select>

                    <p style="padding-top: 10px;"></p>  

                    <button type="submit" class="btn">Salvar</button>
                    <button type="button" class="btn cancel" onclick="closeForm()">Cancelar</button>
                </form>
            </div>
         {% endfor %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Tipo lançamento</th>
                <th scope="col">Valor</th>
                <th scope="col">Usuario</th>
                <th scope="col">Data</th>
                <th scope="col"> </th>
              </tr>
            </thead>
            <tbody>
                {% for financa in financas %}
                    <tr>
                        <td>{{financa.FinancaName}}</td>
                        {% if financa.FinancaType == True %}
                            <td>Entrada</td>
                        {% else %}
                            <td>Saida</td>
                        {% endif %}
                        <td>R$ {{financa.FinancaValue}}</td>
                        <td>{{financa.FinancaUser}}</td>
                        <td>{{financa.FinancaDateUpdate}}</td>
                        <td><button class="btn btn-dark" onclick="openForm{{financa.FinancaID}}()">Editar</button></td>
                      </tr>
                {% endfor %}
            </tbody>
          </table>
         
    </div>
    

    <script>
        function openForm() {
            if (document.getElementById("myForm").style.display == "none"){
                {% for financa in financas %}
                    if (document.getElementById("myForm{{financa.FinancaID}}").style.display == "block"){
                        document.getElementById("myForm{{financa.FinancaID}}").style.display = "none"
                    }
                {% endfor %}
                document.getElementById("myForm").style.display = "block";
            } else {
                document.getElementById("myForm").style.display = "none";
            }
            
        }

        function closeForm() {
            document.getElementById("myForm").style.display = "none";
        }

        {% for financa in financas %}
            function openForm{{financa.FinancaID}}() {
                
                if (document.getElementById("myForm{{financa.FinancaID}}").style.display == "none"){
                    document.getElementById("myForm").style.display = "none";
                    document.getElementById("myForm{{financa.FinancaID}}").style.display = "block";
                } else {
                    document.getElementById("myForm").style.display = "none";
                    document.getElementById("myForm{{financa.FinancaID}}").style.display = "none";
                }
                
            }

            function closeForm{{financa.FinancaID}}() {
                document.getElementById("myForm").style.display = "none";
                document.getElementById("myForm{{financa.FinancaID}}").style.display = "none";
            }
        

        {% endfor %}
    </script>

    
{% endblock %}